# Generated by Django 2.1.2 on 2018-11-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verandaapp', '0003_remove_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.TextField(default='#FFFFFF', max_length=7),
        ),
    ]
