# Generated by Django 2.1.2 on 2018-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verandaapp', '0004_note_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
