# Generated by Django 2.1.2 on 2018-11-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verandaapp', '0007_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
